version: '3.8'

services:
  clickhouse:
    container_name: clickhouse-srv-local
    image: clickhouse/clickhouse-server:latest-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      # Автоматическая инициализация: положите solution.sql в ./init/
      - ./init:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"  # HTTP (включая /play)
      - "9000:9000"  # Native client
    networks:
      - data-pipeline

  kafka:
    image: apache/kafka-native
    container_name: kafka-broker
    ports:
      - "9092:9092"  # для хоста
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - data-pipeline

  console:
    container_name: redpanda-console
    image: docker.redpandadata.com/console:latest
    networks:
      - data-pipeline
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9093"]
    ports:
      - "8080:8080"
    depends_on:
      - kafka

volumes:
  clickhouse-data:
  clickhouse-logs:

networks:
  data-pipeline: